environment.yml, estimagic/optimization/optimize.py, estimagic/optimization/utilities.py, meta.yaml, tox.ini
It might be the case that I am just to stupid as I am always confused by the names of the optimization algorithms. Thus, ``estimagic`` must help me by interpreting my request.
If I enter an invalid algorithm like ``scipy_L-BGFS-B`` (yes, it is really incorrect - you are welcome 😄), the new function ``propose_algorithms`` returns the three most likely algorithms which are shown in the error message.
=> Propose algorithms if an invalid algo is requested

estimagic/dashboard/server_functions.py
The problem occurred on Windows when the dashboard is started in a new process instead of a thread.  Because of some unpickable objects, the dashboard never opens. That is because, multiprocessing on Windows is handled differently than on Linux and MacOS. On the latter, ``fork()`` is called and the fork is able to see whatever exists in the main process at call time. On Windows objects must be pickable to be transferred from the main process to the newly spawned process.
- https://stackoverflow.com/a/38236630/7523785
- https://stackoverflow.com/a/9671030/7523785
=> Fix pickling error in multiprocessing for dashboard on Windows.

docs/source/estimation.rst, estimagic/optimization/optimize.py
Currently, the options are only passed for ``scipy``, but we also use ``pygmo``'s and ``nlopt``'s algorithms. They do not have the same API for that.
closes #3
=> Pass down algo_options for nlopt and pygmo.

docs/source/estimation.rst, estimagic/optimization/process_constraints.py
Providing a value if one wants to fix a parameter should be optional, because most of the time the fixed value is identical to the one in ``params``. This leads to unnecessary duplication.
To be explicit, a warning is raised if the constraint is not accompanied by a value.
=> Providing a value for fixed parameters is optional.

estimagic/optimization/reparametrize.py, estimagic/optimization/utilities.py, estimagic/tests/optimization/test_utilities.py, setup.py
closes #67 
Add a robust cholesky decomposition that works for semi-definite covariance matrices
Tasks
In the process I added a few more functions to `estimagic.optimization.utilities` and made the code prettier.
=> Add robust cholesky and tests.

estimagic/optimization/reparametrize.py
If you fix a parameter and there is already a different value in ``params``, the estimation output does not return the fixed value, but the original entry.
=> Fixed values should appear in estimation output.

docs/source/optimization/constraints.ipynb, estimagic/optimization/process_constraints.py
When I used pairwise equality constraints in skillmodels, I realized that the implementation is much smarter than I had thought and documented.
=> Correct the documentation on pairwise equality constraints.

docs/source/optimization/constraints.ipynb
While teaching myself, I updated the example a little (*value* instead of *bla*, numbers instead of letters in the data) and tried to be a bit more explicit here and there. 
Re-ordered the constraints s.t. the simplest one is first and the example from the top of the page and Robinson Crusoe are not mixed.
Left one case out because I did not have time to actually check what is happening.
=> Make the constraints NB more readable.

estimagic/optimization/check_constraints.py, estimagic/optimization/consolidate_constraints.py, estimagic/optimization/process_constraints.py, setup.py
The new `process_constraints` sometimes fixes all equality constrained parameters, but the first one has to remain free. This is due to a bug in the consolidation of equality constraints. 
In skillmodels I have to call `process_constraints` with a params DataFrame where all entries in the "value" columns are np.nan. This raised an error because the constraints are not fulfilled. Now the checks are only performed if at least one "value" is not missing.
=> Adjustments Needed for Skillmodels + Bug Fixes

.readthedocs.yml, docs/environment.yml, docs/source/conf.py, estimagic/optimization/optimize.py, readthedocs.yml, tox.ini
The conda environment takes more memory than the 2GB provided by rtd and thus, the build sometimes crashes. The changes make the documentation more static by mocking imports and using the notebooks as they are and reducing packages in the environment.
- The documentation has its own, smaller environment. Imports of NumPy, etc. are mocked.
- sphinx check are now executed on Linux
- Warnings while building docs are displayed but are not recognized as errors. Needs to be resolved at some other point in time.
=> Fix memory consumption error on rtd.

.pre-commit-config.yaml, estimagic/estimation/estimate.py, estimagic/logging/create_database.py
There are two fixes necessary to the interface implementation.
- The initial entry in the comparison plot data has to be a DataFrame whereas the remaining entries are NumPy Arrays of the ``"value"`` column. I forgot to save the DataFrame to the database.
- The conversion from mean log like to log like needed the number of contributions. This was unstable as the user-defined criterion function could have one or two returns.
=> Fix ML estimation implemented in #107.

estimagic/parameters/check_constraints.py, estimagic/parameters/process_constraints.py, estimagic/tests/parameters/test_process_constraints.py
Empty constraints (i.e. constraints that did not select any parameters in their loc or query field) were dragged along during the whole constraints processing. In some cases, they could lead to problems.
Dropping empty constraints becomes one of the first steps of the constraint processing.
The diff is a bit cluttered because pycharm once went too far with automatic renaming in comments and I corrected that.
=> Automatically drop empty constraints.

docs/source/development/roadmap.rst, docs/source/getting_started/installation.rst, docs/source/how_to_guides/optimization/how_to_specify_algorithm_and_algo_options.rst, estimagic/optimization/cyipopt_optimizers.py
Only necessary fixes to have a decent presentation of ipopt in the estimagic documentation. No nice formatting etc. yet.
This PR also adds the NLOPT documentation to the how to guide on algorithm choice and algorithm options.
=> Fix ipopt documentation and add nlopt documentation.

docs/source/getting_started/installation.rst, docs/source/how_to_guides/optimization/how_to_specify_algorithm_and_algo_options.rst, environment.yml, src/estimagic/optimization/fides_optimizers.py, tests/optimization/test_fides_options.py, tox.ini
I have adjusted the interface and the tests for the latest Fides version. 
The RuntimeWarnings when some parameters are unbounded still persist. I opened [a Fides Issue](https://github.com/fides-dev/fides/issues/46) for this.
=> Switch to Fides >= 0.7.1

.conda/meta.yaml, CHANGES.rst, docs/source/conf.py, docs/source/development/styleguide.rst, environment.yml, setup.cfg, src/estimagic/optimization/optimize.py, src/estimagic/optimization/tiktak.py, tests/optimization/test_tiktak.py, tox.ini
In this PR, we get rid of the `chaospy` dependency and rewrite the function [`draw_exporation_sample()`](https://github.com/OpenSourceEconomics/estimagic/blob/7484225bb7e86d28c4ab6a933a1c86943878f493/src/estimagic/optimization/tiktak.py#L222). 
As an alternative to the sampling schemes provided by `chaospy`, we make use of `scipy`'s [Quasi-Monte Carlo module](https://scipy.github.io/devdocs/reference/stats.qmc.html), which offers support for low discrepancy sequences.
To-Do
=> Remove chaospy dependency

.github/workflows/main.yml, docs/source/explanations/optimization/internal_optimizers.rst, docs/source/how_to_guides/optimization/how_to_specify_algorithm_and_algo_options.rst, src/estimagic/decorators.py, src/estimagic/optimization/__init__.py, src/estimagic/optimization/bhhh.py, src/estimagic/optimization/cyipopt_optimizers.py, src/estimagic/optimization/fides_optimizers.py, src/estimagic/optimization/get_algorithm.py, src/estimagic/optimization/internal_criterion_template.py, src/estimagic/optimization/nag_optimizers.py, src/estimagic/optimization/neldermead.py, src/estimagic/optimization/nlopt_optimizers.py, src/estimagic/optimization/optimize.py, src/estimagic/optimization/pounders.py, src/estimagic/optimization/pygmo_optimizers.py, src/estimagic/optimization/scipy_optimizers.py, src/estimagic/optimization/tao_optimizers.py, src/estimagic/optimization/tiktak.py, tests/optimization/test_bhhh.py, tests/optimization/test_fides_options.py, tests/optimization/test_internal_criterion_and_derivative_template.py, tests/optimization/test_ipopt_options.py, tests/optimization/test_neldermead.py, tests/optimization/test_tiktak.py, tests/test_decorators.py, tests/test_utilities.py
The internal optimizer interface is flexible but relies on two unintuitive concepts (algorithm_info and partialling a "task"). Moreover, collecting algorithms is difficult and requires many if conditions. 
- The `mark_minimizer` decorator replaces the algorithm_info and also makes the collection of algorithms much simpler
- Instead of having `criterion_and_derivative` as argument in all algorithms, algorithms can now take `criterion`, `derivative`, `criterion_and_derivative` or any subset of those three as arguments.
=> New internal-optimizer-interface

src/estimagic/batch_evaluators.py, src/estimagic/decorators.py, src/estimagic/differentiation/generate_steps.py, src/estimagic/optimization/__init__.py, src/estimagic/optimization/bhhh.py, src/estimagic/optimization/cyipopt_optimizers.py, src/estimagic/optimization/error_penalty.py, src/estimagic/optimization/fides_optimizers.py, src/estimagic/optimization/get_algorithm.py, src/estimagic/optimization/internal_criterion_template.py, src/estimagic/optimization/nag_optimizers.py, src/estimagic/optimization/neldermead.py, src/estimagic/optimization/nlopt_optimizers.py, src/estimagic/optimization/optimize.py, src/estimagic/optimization/pounders.py, src/estimagic/optimization/pygmo_optimizers.py, src/estimagic/optimization/tao_optimizers.py, src/estimagic/optimization/tiktak.py, src/estimagic/parameters/conversion.py, src/estimagic/process_user_function.py, tests/optimization/test_error_penalty.py, tests/optimization/test_internal_criterion_and_derivative_template.py, tests/optimization/test_many_algorithms.py, tests/optimization/test_tiktak.py, tests/parameters/test_conversion.py, tests/test_decorators.py
collect the optimizer histories (for criterion values and parameter vectors that have been tried) during optimization and add them to the result. 
For now, this will only worked for optimizers that do not parallelize. It will however work with parallel numerical derivatives or parallel multistart optimizations.
This is a preparation for #323 and #314
=> Collect histories and add them to output of optimization

src/estimagic/benchmarking/get_benchmark_problems.py, src/estimagic/benchmarking/process_benchmark_results.py, src/estimagic/benchmarking/run_benchmark.py, src/estimagic/optimization/internal_criterion_template.py, src/estimagic/visualization/profile_plot.py, tests/benchmarking/test_run_benchmark.py, tests/visualization/test_convergence_plot.py, tests/visualization/test_profile_plot.py
This PR improves estimagic's benchmarking functionality and closes #314. 
To-Dos:
=> Improve Benchmarking

CHANGES.rst, docs/source/index.rst, src/estimagic/estimation/estimate_ml.py, src/estimagic/estimation/estimate_msm.py, src/estimagic/inference/shared.py, src/estimagic/optimization/optimize.py, src/estimagic/optimization/optimize_result.py, src/estimagic/parameters/consolidate_constraints.py, src/estimagic/parameters/process_selectors.py, src/estimagic/utilities.py, src/estimagic/visualization/estimation_table.py, src/estimagic/visualization/slice_plot.py, tests/estimation/test_estimate_ml.py, tests/estimation/test_estimate_msm.py, tests/optimization/test_optimize_result.py, tests/test_utilities.py, tests/visualization/test_slice_plot.py
Fixes and tests for multiple edge cases that were not covered before
- Supress pandas performance warning during constraint processing
- Supress fuzzywuzzy performance warning
- Fix bug in consolidate constraint that lead to an exception if equality constraints and fixes are overlapping
- Add cloudpickle based `to_pickle` method to estimation results. This is necessary because standard pickle would fail. For consistency, we also add it to optimization result. 
- Fix a bug in generation of estimation `summary` dataframe; This could have lead to wrong results (internal instead of external parameter values) if both parameter vectors have the same length. It lead to exceptions otherwise. 
- Allow for functions that return dictionaries in slice_plot.
- Fix a small bug in `render_latex`.
=> Multiple fixes

src/estimagic/optimization/subsolvers/_steihaug_toint_quadratic.py, tests/optimization/test_pounders_integration.py
Remove problematic test case for conjugate gradient method ```steihaug-toint``` and subsolver ```bntr```.
=> Fix pounders test cases

src/estimagic/optimization/pounders.py, src/estimagic/optimization/tranquilo/fit_models.py, src/estimagic/optimization/tranquilo/tranquilo.py
=> Polish tranquilo interface

.pre-commit-config.yaml, src/estimagic/optimization/tranquilo/aggregate_models.py, src/estimagic/optimization/tranquilo/filter_points.py, src/estimagic/optimization/tranquilo/fit_models.py, src/estimagic/optimization/tranquilo/models.py, src/estimagic/optimization/tranquilo/tranquilo.py, tests/optimization/tranquilo/test_aggregate_models.py, tests/optimization/tranquilo/test_filter_points.py, tests/optimization/tranquilo/test_models.py, tests/optimization/tranquilo/test_tranquilo.py
=> Refactor tranquilo code

src/estimagic/optimization/tiktak.py, tests/optimization/test_multistart.py, tests/optimization/test_tiktak.py
=> Fix bug in multistart with least-squares optimizers

src/estimagic/optimization/tranquilo/poisedness.py, tests/optimization/tranquilo/test_poisedness.py
Mini PR to polish the poisedness module.
=> Polish poisedness

src/estimagic/optimization/tranquilo/filter_points.py, src/estimagic/optimization/tranquilo/fit_models.py, src/estimagic/optimization/tranquilo/get_component.py, src/estimagic/optimization/tranquilo/sample_points.py, src/estimagic/optimization/tranquilo/tranquilo.py, tests/optimization/tranquilo/test_filter_points.py, tests/optimization/tranquilo/test_get_component.py
Tranquilo consists of many interchangeable components.  Usually a component is a partialled function (provided by the user or loaded from a dictionary of built in functions). Sometimes, not all supported functions have the same signature and the processed function needs to ignore unused arguments. 
Write a get_component function that covers most of our use-cases.
=> Refactor getter functions

.envs/testenv-linux.yml, .envs/testenv-others.yml, docs/source/conf.py, environment.yml, setup.cfg, src/estimagic/utilities.py, tests/test_utilities.py
Rewrote the propose_alternatives function using difflib
Added some simple unit tests for it
Removed fuzzywuzzy from environment.yml and setup.cfg
=> Replace fuzzywuzzy

src/estimagic/optimization/tranquilo/aggregate_models.py, src/estimagic/optimization/tranquilo/bounds.py, src/estimagic/optimization/tranquilo/estimate_variance.py, src/estimagic/optimization/tranquilo/fit_models.py, src/estimagic/optimization/tranquilo/geometry.py, src/estimagic/optimization/tranquilo/models.py, src/estimagic/optimization/tranquilo/options.py, src/estimagic/optimization/tranquilo/region.py, src/estimagic/optimization/tranquilo/sample_points.py, src/estimagic/optimization/tranquilo/solve_subproblem.py, src/estimagic/optimization/tranquilo/tranquilo.py, src/estimagic/optimization/tranquilo/volume.py, src/estimagic/optimization/tranquilo/weighting.py, src/estimagic/visualization/deviation_plot.py, src/estimagic/visualization/visualize_tranquilo.py, tests/optimization/tranquilo/test_acceptance_decision.py, tests/optimization/tranquilo/test_bounds.py, tests/optimization/tranquilo/test_estimate_variance.py, tests/optimization/tranquilo/test_filter_points.py, tests/optimization/tranquilo/test_fit_models.py, tests/optimization/tranquilo/test_geometry.py, tests/optimization/tranquilo/test_models.py, tests/optimization/tranquilo/test_region.py, tests/optimization/tranquilo/test_rho_noise.py, tests/optimization/tranquilo/test_sample_points.py, tests/optimization/tranquilo/test_tranquilo.py, tests/optimization/tranquilo/test_volume.py
In this PR, we clean up certain components of tranquilo:
1. We create a new module `bounds.py` for the `Bounds` dataclass.
1. We create a new module `region.py` for the `Region` dataclass
1. The region class is now aware of its shape, which is a sphere if bounds aren't binding and a cube otherwise
1. The region class now provides methods `map_to_unit` and `map_from_unit` for transitioning between the unit space used in points sampling, fitting, and solving the subproblem, and the regular trustregion space.
1. The sampling code now adaptively samples from the correct shape using the new shape information of the trustregion.
1. We replace the class `ModelInfo` with the string `model_type` which can only be either `linear` or `quadratic`.
=> Tranquilo cleanup

src/estimagic/optimization/pounders_auxiliary.py, src/estimagic/optimization/subsolvers/bntr.py, src/estimagic/optimization/subsolvers/bntr_fast.py, src/estimagic/optimization/subsolvers/gqtpar.py, src/estimagic/optimization/subsolvers/gqtpar_fast.py, src/estimagic/optimization/tranquilo/process_arguments.py, src/estimagic/optimization/tranquilo/solve_subproblem.py, src/estimagic/optimization/tranquilo/wrapped_subsolvers.py, tests/optimization/subsolvers/test_bntr_fast.py, tests/optimization/test_quadratic_subsolvers.py, tests/optimization/tranquilo/test_rho_noise.py, tests/optimization/tranquilo/test_solve_subproblem.py
This PR updates the `solve_subproblem.py` module and subsolver code.
=> Adjust subsolver module to components interface

.envs/update_envs.py
- On Windows, the environment files created by `update_envs` have CRLF line endings.
- In particular, this leads to problems with the `mixed-line-ending` hook.
- This PR makes sure that LF line endings are used by opening the file in binary mode. 
- I am of course open for other solutions.
=> adjust `update_envs` to make sure that created files have LF line endings

src/estimagic/benchmarking/process_benchmark_results.py
```x_precision``` and ```y_precision``` in  ```process_benchmark_results``` should always be of type ```float```.
=> Update docstrings in process_benchmark_results

src/estimagic/estimation/msm_weighting.py, tests/estimation/test_msm_weighting.py
Fixes #472 and adds a test case.
=> Pass bootstrap_kwargs to bootstrap call in get_moments_cov

src/estimagic/estimation/estimate_msm.py, src/estimagic/estimation/msm_weighting.py, tests/estimation/test_msm_weighting.py
Added the identity weighting matrix to the MSM estimation:
- First change made is to the `get_weighting_matrix()` function to allow for the identity matrix
- Second change permits `"identity"` as a valid option for weights in `estimate_msm()`
=> Identity Weighting Matrix

docs/rtd_environment.yml
In this PR, I fix the API section in the documentation.
In particular, I restrict plotly to version 5.18 or lower.
When using 5.19, autodoc returned the following error, which is raised in plotly-code that was newly introduced in version 5.19:
```console
WARNING: autodoc: failed to import function 'convergence_plot' from module 'estimagic'; the following exception was raised:
Traceback (most recent call last):
File "/home/tim/miniforge3/envs/estimagic-docs/lib/python3.9/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
return importlib.import_module(modname)
File "/home/tim/miniforge3/envs/estimagic-docs/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", …
```
=> Fix API section in docs

docs/rtd_environment.yml, docs/source/conf.py
In this PR, we fix the API section of the documentation.
In our documentation, we use [mock imports](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports). From the sphinx docs:
> This is useful when some external dependencies are not met at build time and break the building process. You may only specify the root package of the dependencies themselves and omit the sub-modules:
However,  _mocked_ modules cannot be used during build time. This was not a problem until a few weeks ago when `plotly` started checking `pandas` version numbers (mocked for our documentation), which requires the execution of `pandas` code --- namely `pandas.__version__` --- during build time. My unawareness of what was actually happening led me to restrict the `plotly` …
=> Fix documentation

README.md
Hello, I thought this was a typo in the main README
=> typo: optimzer => optimizer

pyproject.toml, src/estimagic/estimation/estimate_msm.py, src/estimagic/visualization/estimation_table.py, tests/estimation/test_estimate_msm.py, tests/visualization/test_estimation_table.py
In this PR, we implement a few fixes.
1. Suppress pandas PerformanceWarnings (before this, we suppressed warnings that occurred in the function `estimation_table`, but these warnings were raised in the function `render_latex`, where we did not suppress them; for reference, see #379 )
2. Add full optimization result to the return object of the `estimate_msm` function. This closes #491.
=> Implement a few fixes

docs/source/explanation/explanation_of_numerical_optimizers.md, docs/source/explanation/internal_optimizers.md, docs/source/explanation/numdiff_background.md
In addition to the minor changes which I already implemented:
- I really like the visualizations in `explanation_of_numerical_optimizers.md`. However, it would be great if there was a way to manually click through the images such that the user can speed it up or revert to a previous figure. With the current implementation via gifs it takes quite a while to see the full cycle.
=> small changes to explanation files in documentation

.github/workflows/main.yml, .pre-commit-config.yaml, .tools/envs/testenv-linux.yml, .tools/envs/testenv-numpy.yml, .tools/envs/testenv-others.yml, .tools/envs/testenv-pandas.yml, .tools/update_envs.py, docs/source/how_to/how_to_multistart.ipynb, environment.yml, pyproject.toml, src/optimagic/differentiation/richardson_extrapolation.py, src/optimagic/optimizers/_pounders/gqtpar.py, src/optimagic/parameters/kernel_transformations.py, tests/optimagic/optimization/test_with_nonlinear_constraints.py
- Make optimagic compatible with numpy>=2
- Test optimagic with numpy<2 and numpy>=2:
1. First test is pandas<2 and numpy<2
2. Second test is pandas>= 2 and numpy<2
3. Perform all other tests with numpy>=2
- Pin mypy (should be the same version as used in the pre-commit hook)
=> Support numpy>=2

.tools/envs/testenv-linux.yml, .tools/envs/testenv-numpy.yml, .tools/envs/testenv-others.yml, .tools/envs/testenv-pandas.yml, docs/source/algorithms.md, docs/source/installation.md, environment.yml, src/optimagic/optimizers/nag_optimizers.py, tests/optimagic/optimization/test_many_algorithms.py
- Fixes results processing of nag optimizers
Closes #538
=> Fix results processing of nag optimizers

.tools/create_algo_selection_code.py, CHANGES.md, src/estimagic/__init__.py, src/optimagic/__init__.py, src/optimagic/algorithms.py, src/optimagic/optimization/algorithm.py, src/optimagic/optimizers/pygmo_optimizers.py, src/optimagic/optimizers/tao_optimizers.py, src/optimagic/visualization/history_plots.py, tests/optimagic/optimization/test_history_collection.py, tests/optimagic/optimization/test_many_algorithms.py, tests/optimagic/optimization/test_with_nonlinear_constraints.py, tests/optimagic/test_algo_selection.py, tests/optimagic/visualization/test_history_plots.py
=> Polish the algo selection tool

src/optimagic/visualization/history_plots.py, tests/optimagic/visualization/test_history_plots.py
While reading the docs on 'How to use logging',
fig = om.criterion_plot("my_log.db") does not produce a figure instead a FileNotFoundError is shown.
This is because input of type str is not handled in _harmonize_inputs_to_dict.
```
om.minimize(
fun= lambda x : x@x,
params=np.arange(5),
algorithm="scipy_lbfgsb",
logging=om.SQLiteLogOptions(
"my_log.db", if_database_exists=om.ExistenceStrategy.REPLACE
),)
fig = om.criterion_plot("test_log.db")
fig.show()
```
Traceback
<details>
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[11], line 1
----> 1 fig = om.criterion_plot("my_log.db")
2 fig.show(renderer="png")
File ~/checkouts/readthedocs.org/user_builds/optimagic/conda/latest/lib/pyt …
=> Bug in _harmonize_inputs_to_dict

src/optimagic/parameters/process_selectors.py
A skillmodels-based project came up with `selected = [1.0, 1.0, 44.0]`, so `_fail_if_duplicates` failed with
```
*** TypeError: list indices must be integers or slices, not float
```
instead of providing information on the problematic constraint.
Fix is to do the conversion to int first, rather than in the line just after the call to `_fail_if_duplicates`.
=> Let `_fail_if_duplicates` raise the correct error.

docs/rtd_environment.yml, docs/source/conf.py, environment.yml
Found the broken numpy doc link in `intersphinx_mapping`, so used [intersphinx-registry](https://pypi.org/project/intersphinx-registry/) to avoid needing to update these links in the future. Also added `scipy` in the list of packages. Please LMK if this is a good change and/or anything needs to be changed.
Thank you :)
=> MAINT: using intersphinx-registry

docs/source/algorithms.md, src/optimagic/logging/logger.py, src/optimagic/optimization/history.py, src/optimagic/optimizers/scipy_optimizers.py
Added the following parameters from SciPy's BFGS optimizer, which where not exposed in the optimagic implementation:   
- **display** (bool): 
Set to True to print convergence messages. Default is False.
- scipy name: **disp**
- **convergence_xtol_rel** (float):
Relative tolerance for `x`. Terminate successfully if step size is less than `xk * xrtol` where `xk` is the current parameter vector. Default is 1e-5.
- scipy name: **xrtol**
- **armijo_condition** (float):
Parameter for Armijo condition rule. Default is 1e-4.
- smaller ⇒ more aggressive steps, larger ⇒ more conservative ones 
- scipy name: **c1**
- **curvature_condition** (float):
Parameter for curvature condition rule. Default is 0.9. 
- smaller ⇒ stricter curvature reduction (smaller steps), larger ⇒ looser (bigger steps)
- …
=> scipy_bfgs params

.tools/envs/testenv-linux.yml, .tools/envs/testenv-numpy.yml, .tools/envs/testenv-others.yml, .tools/envs/testenv-pandas.yml, docs/source/algorithms.md, docs/source/refs.bib, environment.yml, pyproject.toml, src/optimagic/algorithms.py, src/optimagic/config.py, src/optimagic/optimizers/nevergrad_optimizers.py
Implements the Particle Swarm Optimization algorithm from `nevergrad`.
Partially fixes #560
=> Add wrapper for Nevergrad PSO optimizer

CHANGES.md, src/optimagic/batch_evaluators.py, src/optimagic/deprecations.py, src/optimagic/differentiation/derivatives.py, src/optimagic/differentiation/numdiff_options.py, src/optimagic/optimization/multistart_options.py, src/optimagic/optimizers/scipy_optimizers.py, src/optimagic/typing.py, tests/optimagic/differentiation/test_numdiff_options.py, tests/optimagic/optimization/test_with_multistart.py
=> Fix the too strict checking of batch evaluator literals for multistart.

.github/workflows/main.yml, .tools/envs/testenv-linux.yml, .tools/envs/testenv-numpy.yml, .tools/envs/testenv-others.yml, .tools/envs/testenv-pandas.yml, .tools/envs/testenv-plotly.yml, .tools/update_envs.py, docs/rtd_environment.yml, environment.yml, pyproject.toml, src/optimagic/visualization/plotting_utilities.py, tests/optimagic/visualization/test_plotting_utilities.py
In the current envs, incompatible versions of plotly and kaleido are installed. See docs here:
https://optimagic.readthedocs.io/en/latest/tutorials/optimization_overview.html#you-can-compare-optimizers
Updating them here.
There are some test failures, but AFAICT in tests that check deprecations / are for deprecated behavior. In particular, it looks like the `slice_plot` requires some plotly-internal representation of data, which seems to have changed. 
It certainly does not seem worth it to fix those tests -- two routes, I guess:
1. Just remove the tests and corresponding code if the deprecations are scheduled to be enforced in the next release
2. Pin `plotly < 6.0` and `kaleido < 0.3` instead of the update done here.
=> Add support for plotly >= 6

docs/source/how_to/how_to_document_optimizers.md
Added a note in the `how_to_document_optimizers` guide about using `from __future__ import annotations` to ensure type hints are rendered correctly in Sphinx.
=> Add note about __future__ import

.tools/envs/testenv-linux.yml, .tools/update_envs.py
pin petsc4py to <= 3.23.4,
Failing test on python 3.11 with error
```
E   [0] Unable to find requested Tao type pounders
petsc4py/PETSc/TAO.pyx:190: Error
```
=> pin petsc4py to <= 3.23.4,  failing test python 3.11

docs/source/how_to/how_to_change_plotting_backend.ipynb, docs/source/how_to/how_to_visualize_histories.ipynb, docs/source/how_to/index.md, src/optimagic/visualization/backends.py
This PR adds documentation on using different plotting backends.
Note: This PR should go **after** #641, as this relies on some fixes made to `criterion_plot()`
1. Created `how_to_change_plotting_backend.ipynb` with information on:
- Supported backends
- Type of the returned figure object
- Simple usage example for  `criterion_plot()` for each backend. 
1. Updated `how_to_visualize_histories.ipynb` with a small section on changing backends.
- Should we document 'advanced' usage (customizing plots after generated by optimagic)?
=> Add how-to change plotting backends guide
