.appveyor.yml
.pre-commit-config.yaml
.travis.yml
docs/source/conf.py
docs/source/estimation.rst
docs/source/introduction.rst
environment.yml
estimagic/estimation/weighting_matrix.py
estimagic/optimization/optimize.py
setup.py
tox.ini

Make estimagic compliant with our linters.
closes #7

Try to fix travis.

---

docs/source/dashboard.rst
docs/source/estimation.rst
docs/source/index.rst
estimagic/dashboard/convergence_tab.py
estimagic/dashboard/dashboard.py
estimagic/dashboard/plotting_functions.py
estimagic/dashboard/server_functions.py
estimagic/optimization/optimize.py
estimagic/optimization/utilities.py
meta.yaml

**Done:** 
- add documentation of the dashboard
- stop updating when minimization finishes
- server thread stops and yields the port when the main script that called it exits (this does not affect the interactions present at the moment). This partially addresses #17.
- add HoverTool showing the iteration, fitness and values of the parameter group.
- styling of the convergence plot (title fontsize, centering, padding around plots, axis labels ...)

Various Dashboard Improvements

---

environment.yml
estimagic/optimization/algo_dict.json
estimagic/optimization/optimize.py
meta.yaml
tox.ini

Wrap the scipy optimizers that accept bound constraints.

Wrap scipy optimizers.

---

.travis.yml
README.rst
docs/source/conf.py

The following changes are made:
- Todos are not displayed on readthedocs
- Readme is fixed and badges are added

Make documentation ready for readthedocs and small improvements to README.rst

---

estimagic/optimization/optimize.py
estimagic/optimization/process_constraints.py
estimagic/optimization/reparametrize.py
estimagic/optimization/start_helpers.py
estimagic/tests/optimization/test_reparametrize.py
estimagic/tests/optimization/test_start_helpers.py
setup.py

Bug fixes and improvements in start_params_helpers.

Skillmodels changes

---

.pre-commit-config.yaml
docs/source/estimation.rst
docs/source/inference.rst
docs/source/optimize.rst
environment.yml
estimagic/differentiation/differentiation.py
estimagic/optimization/optimize.py
estimagic/optimization/reparametrize.py
estimagic/tests/optimization/test_reparametrize.py
setup.py
tox.ini

Closes #13.
This PR implements two scaling features for the parameter vector of the optimization. Parameters can either be scaled by starting values or gradients.

Implement scaling for parameter vector of optimization.

---

docs/source/differentiation.rst
environment.yml
estimagic/differentiation/differentiation.py
estimagic/optimization/optimize.py
estimagic/tests/differentiation/test_differentiation.py
setup.py

Pass more arguments to numdifftools

---

.azure-pipelines.yml
estimagic/optimization/optimize.py

Added the following import and logic to ignore the pandas performance warnings
from warnings import simplefilter
simplefilter(action='ignore', category=pd.errors.PerformanceWarning)

Updated optimize.py to ignore performance warnings

---

.gitignore
docs/source/optimization/constraints/constraints.ipynb
docs/source/optimization/constraints/selecting_parameters.ipynb
docs/source/rtd_environment.yml

I had forgotten to commit them because notebooks were on the .gitignore. Now I add them and changed the .gitignore.

Add documentation notebooks

---

docs/source/getting_started/ordered_logit_example.ipynb
estimagic/dashboard/convergence_tab.py
estimagic/dashboard/dashboard.py
estimagic/dashboard/server_functions.py
estimagic/examples/logit.py
estimagic/optimization/optimize.py
estimagic/optimization/process_arguments.py
estimagic/optimization/process_constraints.py
estimagic/optimization/utilities.py
estimagic/tests/optimization/test_parallel_optimizations.py
estimagic/tests/optimization/test_process_arguments.py

Miscellaneous small improvements

---

estimagic/decorators.py
estimagic/logging/create_database.py
estimagic/logging/update_database.py
estimagic/optimization/optimize.py

Two changes:
- handle_exceptions is not partialed anymore.
- logging_decorator works without parentheses.

Small fixes to decorators.

---

docs/environment.yml
docs/source/conf.py
environment.yml
estimagic/optimization/check_arguments.py

The former does not recognize partialed functions as a correct type.

Replace types.FunctionType with typing.Callable.

---

.github/ISSUE_TEMPLATE/enhancement.md
environment.yml
meta.yaml
tox.ini

- Restrict pandas to >=0.24 and <1.0 in meta.yaml and other files. Otherwise conda build fails. See #143 
- Add enhancement issue template from respy

Small Fixes

---

docs/source/how_to_guides/optimization/how_to_specify_parameters.rst
estimagic/differentiation/derivatives.py
estimagic/optimization/check_constraints.py
estimagic/optimization/consolidate_constraints.py
estimagic/optimization/optimize.py
estimagic/optimization/process_constraints.py
estimagic/tests/conftest.py
estimagic/tests/optimization/fixtures/reparametrize_fixtures.csv
estimagic/tests/optimization/test_all_algorithms_with_sum_of_squares.py
estimagic/tests/optimization/test_broadcast_arguments.py
estimagic/tests/optimization/test_parallel_optimizations.py
estimagic/tests/optimization/test_process_constraints.py
estimagic/tests/optimization/test_reparametrize.py
estimagic/tests/optimization/test_tao_optimizers.py
estimagic/tests/test_decorators.py

fix issues #138 and #139
Therefore the constraints key words for lower and upper bounds are adjusted and the values of the bounds are converted to float.

fix issues #138 and #139

---

docs/source/how_to_guides/optimization/how_to_use_logging.ipynb
docs/source/reference_guides/optimization.rst
estimagic/dashboard/monitoring_app.py
estimagic/logging/database_utilities.py
estimagic/logging/read_log.py
estimagic/tests/logging/test_read_log.py

- Add high level functions to read from the optimization log
- Add a tutorial that shows how to work with the optimization log

Add high level log reading function.

---

estimagic/config.py
estimagic/dashboard/plot_functions.py
estimagic/tests/dashboard/test_plot_functions.py
estimagic/tests/visualization/test_colors.py
estimagic/visualization/colors.py

We already used parts of the color palettes in the dashboard, but now I add the full `get_colors` function.

Add color palettes from impact lab

---

estimagic/dashboard/plot_functions.py

Fix the default plot width of dashboard plots. It was zero/None

Fix plot width.

---

docs/source/explanations/differentiation/index.rst
docs/source/explanations/differentiation/richardson_extrapolation.rst
estimagic/differentiation/derivatives.py
estimagic/logging/read_log.py
estimagic/optimization/internal_criterion_template.py
estimagic/optimization/tao_optimizers.py
estimagic/tests/differentiation/test_derivatives.py

Implements ability to return function evaluations plus information on steps from the derivative function in a tidy data frame.

Return func evals and info as tidy frame

---

estimagic/visualization/estimation_table.py

make estimation table more flexible with respect to inputs, render some attributes optional.

Estimation table flex

---

.pre-commit-config.yaml
MANIFEST.in
README.rst
docs/environment.yml
docs/source/conf.py
docs/source/development/roadmap.rst
docs/source/explanations/differentiation/richardson_extrapolation.rst
docs/source/explanations/optimization/implementation_of_constraints.rst
docs/source/explanations/optimization/tests_for_supported_optimizers.rst
docs/source/getting_started/when_not_use_estimagic.rst
docs/source/how_to_guides/optimization/how_to_scale_optimization_problems.rst
docs/source/how_to_guides/optimization/how_to_specify_algorithm_and_algo_options.rst
docs/source/how_to_guides/optimization/how_to_specify_constraints.rst
docs/source/refs.bib
environment.yml
estimagic/__init__.py
estimagic/logging/database_utilities.py
estimagic/optimization/nag_optimizers.py
estimagic/optimization/optimize.py
estimagic/parameters/consolidate_constraints.py
estimagic/tests/optimization/test_all_algorithms_with_sum_of_squares.py
setup.cfg

- Add some pre-commit hooks.
- Add some top-level imports to import lower-level functions like ``robust_cholesky``.
- Some cleanups.

Add some enhancements.

---

.github/workflows/continuous-integration-workflow.yml
tox.ini

xref: https://github.com/OpenSourceEconomics/pybaum/pull/7

Remove pre-commit from actions.

---

src/estimagic/estimation/estimate_ml.py
src/estimagic/estimation/estimate_msm.py

Small bugfix to make it actually possible to calculate standard errors when optimization is done outside of the estimation function.

Fix estimation with external optimization.

---

docs/rtd_environment.yml
docs/source/how_to_guides/optimization/how_to_specify_algorithm_and_algo_options.rst
docs/source/refs.bib
tox.ini

In this PR, we fix minor CI issues with ``sphinx`` and update broken links in the documentation.

Fix minor CI issues and update links in docs

---

src/estimagic/visualization/estimation_table.py
tests/visualization/test_estimation_table.py

Fixing a small bug in estimation_table

---

src/estimagic/optimization/tranquilo/aggregate_models.py
src/estimagic/optimization/tranquilo/fit_models.py
src/estimagic/optimization/tranquilo/models.py
src/estimagic/optimization/tranquilo/tranquilo.py
tests/optimization/tranquilo/test_aggregate_models.py
tests/optimization/tranquilo/test_fit_models.py

Before we stored coefficients of quadratic model using `a, b, C` such that
```python
f(x) = a + b.T x + x.T C x
```
Now we store coefficients using `a, g, H` such that 
```python
f(x) = a + g.T x + 0.5 * x.T H x
```
where `H = C + C.T`. This allows us to interpret `H` as the `hessian(f)(x)`.

Use Hessian to store polynomial coefficients

---

CHANGES.rst
docs/source/algorithms.rst
docs/source/changes.rst
docs/source/development/changes.rst
docs/source/development/credits.rst
docs/source/development/index.rst
docs/source/explanations/optimization/index.rst
docs/source/index.rst
docs/source/reference_guides/index.rst
src/estimagic/__init__.py
src/estimagic/estimation/estimate_ml.py
src/estimagic/estimation/estimate_msm.py
src/estimagic/optimization/optimize.py
src/estimagic/optimization/optimize_result.py
src/estimagic/sensitivity/msm_sensitivity.py
src/estimagic/visualization/estimation_table.py

Update results object documentation

---

docs/rtd_environment.yml
docs/source/refs.bib
src/estimagic/optimization/tranquilo/fit_models.py
tests/optimization/tranquilo/test_adjust_radius.py
tests/optimization/tranquilo/test_fit_models.py

Add the POUNDERS fitting method to tranquilo.

Add pounders fitting

---

docs/source/refs.bib
environment.yml
tox.ini

Fix broken reference and pin ```simoptlib==1.0.1```.

Fix broken link in docs.

---

src/estimagic/estimate_ml.py
src/estimagic/estimate_msm.py
src/optimagic/optimization/internal_criterion_template.py
src/optimagic/optimization/optimize.py
src/optimagic/optimization/process_results.py
src/optimagic/parameters/nonlinear_constraints.py
src/optimagic/visualization/history_plots.py
tests/estimagic/test_msm_sensitivity.py
tests/optimagic/differentiation/test_compare_derivatives_with_jax.py
tests/optimagic/differentiation/test_derivatives.py
tests/optimagic/differentiation/test_generate_steps.py
tests/optimagic/optimization/test_error_penalty.py
tests/optimagic/optimization/test_params_versions.py
tests/optimagic/parameters/test_block_trees.py
tests/optimagic/parameters/test_kernel_transformations.py
tests/optimagic/parameters/test_scale_conversion.py
tests/optimagic/parameters/test_space_conversion.py

Fixes deprecation warnings that were missed in #514

Fix deprecation warnings stemming from derivatives

---

docs/source/algorithms.md
src/optimagic/optimizers/scipy_optimizers.py

Adding option to the dataclass of the algorithm plus changing the documentation.

Adding missing display option to scipy_slsqp

---

docs/source/algorithms.md
src/optimagic/optimizers/scipy_optimizers.py

Added the Scipy disp parameter to the following optimizers:
scipy_neldermead
scipy_powell
scipy_conjugate_gradient
scipy_newton_cg
scipy_cobyla
scipy_truncated_newton
scipy_trust_constr

Scipy disp parameter

---

environment.yml
src/optimagic/optimizers/scipy_optimizers.py

Fix results processing so it works for new cobyla.
